site_name: Holy Light
site_description: >-

site_url: https://light.ardi.gg/

repo_name: hardlyardi/light
repo_url: https://github.com/hardlyardi/light

edit_uri: edit/main/docs/

theme:
  name: material

  logo: assets/images/light.png
  favicon: assets/images/light.svg

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Lights are on

    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Lights are off

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.instant.preview

    - navigation.indexes

    - navigation.tabs

    - navigation.path

    - navigation.top

    - navigation.footer

    - search.suggest
    - search.highlight
    - search.share

    - announce.dismiss

    - content.tooltips

    - content.action.edit
    - content.action.view

    - content.code.copy
    - content.code.annotate
    - content.code.select

    - content.footnote.tooltips

  icon:
    repo: fontawesome/brands/github
    tag:
      server: material/server-network
      client: material/account-network-outline
      shared: material/script-text-outline
      sync: material/sync
      async: material/clock
      errors: material/alert-circle-outline
      experimental: material/flask

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-WJ3WTV5DDW
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: I've been blessed reading this
          data: 4
          note: >-
            Mrrp meow the cat ate ur feedback:
            <PRE><tt>ï¼lã€<br>ï¼ˆï¾Ÿï½¤ ï½¡ï¼—<br>  lã€ï¾~ãƒ½<br>     ã˜ã—f_,)ãƒ</tt></PRE>
            <img src="https://raw.githubusercontent.com/hardlyardi/light/main/docs/assets/images/the_cat.jpg" alt="Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow"> 
            <br>...Though, if you have anything more to say, please visit the <a href="https://docs.google.com/forms/d/e/1FAIpQLSeOxVTHsijUPxAYUXJMvb0fCjYfNgHyMu7Hh310LqvLgFLG7Q/viewform?usp=header" target="_blank">feedback form</a>. <small>(Yes, Seriously.)</small>

        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 3
          note: >-
            Mrrp meow the cat ate ur feedback:
            <PRE><tt>ï¼lã€<br>ï¼ˆï¾Ÿï½¤ ï½¡ï¼—<br>  lã€ï¾~ãƒ½<br>     ã˜ã—f_,)ãƒ</tt></PRE>
            <img src="https://raw.githubusercontent.com/hardlyardi/light/main/docs/assets/images/the_cat.jpg" alt="Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow"> 
            <br>...Though, if you have anything more to say, please visit the <a href="https://docs.google.com/forms/d/e/1FAIpQLSeOxVTHsijUPxAYUXJMvb0fCjYfNgHyMu7Hh310LqvLgFLG7Q/viewform?usp=header" target="_blank">feedback form</a>. <small>(Yes, Seriously.)</small>

        - icon: material/emoticon-neutral-outline
          name: This page is alright
          data: 2
          note: >-
            Mrrp meow the cat ate ur feedback:
            <PRE><tt>ï¼lã€<br>ï¼ˆï¾Ÿï½¤ ï½¡ï¼—<br>  lã€ï¾~ãƒ½<br>     ã˜ã—f_,)ãƒ</tt></PRE>
            <img src="https://raw.githubusercontent.com/hardlyardi/light/main/docs/assets/images/the_cat.jpg" alt="Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow"> 
            <br>...Though, if you have anything more to say, please visit the <a href="https://docs.google.com/forms/d/e/1FAIpQLSeOxVTHsijUPxAYUXJMvb0fCjYfNgHyMu7Hh310LqvLgFLG7Q/viewform?usp=header" target="_blank">feedback form</a>. <small>(Yes, Seriously.)</small>

        - icon: material/emoticon-sad-outline
          name: This page wasn't helpful
          data: 1
          note: >-
            Mrrp meow the cat ate ur feedback:
            <PRE><tt>ï¼lã€<br>ï¼ˆï¾Ÿï½¤ ï½¡ï¼—<br>  lã€ï¾~ãƒ½<br>     ã˜ã—f_,)ãƒ</tt></PRE>
            <img src="https://raw.githubusercontent.com/hardlyardi/light/main/docs/assets/images/the_cat.jpg" alt="Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow"> 
            <br>...Though, if you have anything more to say, please visit the <a href="https://docs.google.com/forms/d/e/1FAIpQLSeOxVTHsijUPxAYUXJMvb0fCjYfNgHyMu7Hh310LqvLgFLG7Q/viewform?usp=header" target="_blank">feedback form</a>. <small>(Yes, Seriously.)</small>

        - icon: material/heart-broken
          name: I hate you
          data: 0
          note: >-
            Mrrp meow the cat ate ur feedback:
            <PRE><tt>ï¼lã€<br>ï¼ˆï¾Ÿï½¤ ï½¡ï¼—<br>  lã€ï¾~ãƒ½<br>     ã˜ã—f_,)ãƒ</tt></PRE>
            <img src="https://raw.githubusercontent.com/hardlyardi/light/main/docs/assets/images/the_cat.jpg" alt="Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow"> 
            <br>...Though, if you have anything more to say, please visit the <a href="https://docs.google.com/forms/d/e/1FAIpQLSeOxVTHsijUPxAYUXJMvb0fCjYfNgHyMu7Hh310LqvLgFLG7Q/viewform?usp=header" target="_blank">feedback form</a>. <small>(Yes, Seriously.)</small>

  consent:
    title: "<h1>S<b><b>light</b></b>ly Annoying ğŸª Popup</h1>"
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. They aren't vital for you to be able to
      read, so don't sweat if you're not a fan of sweet things.
    actions:
      - accept
      - reject
      - manage

  social:
    - icon: fontawesome/brands/github
      link: https://light.ardi.gg/github
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@hardlyardi
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/331399684415553538
    - icon: material/butterfly-outline
      link: https://bsky.app/profile/ardidasillygoose.bsky.social

  tags:
    Server: server
    Client: client
    Shared: shared
    Synchronous: sync
    Yielding: async
    Errors: errors
    Experimental: experimental

hooks:
  - docs/overrides/hooks/shortcodes.py

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html

  - pymdownx.betterem
  - pymdownx.details

  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite

  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - typeset
  - tags:
      tags_allowed:
        - Server
        - Client
        - Shared
        - Synchronous
        - Yielding
        - Errors
        - Experimental
        - Internal

  - social:
      enabled: !ENV [CI, false] # only should be built in CI
      debug: false # doesn't apply to builds, only in testing

      cards_layout_dir: docs/layouts/
      cards_layout: social_card

nav:
  - Home: index.md
  - Quick Start / Get Started:
      - Install: quick-start/index.md
      - Beginner's Guide: quick-start/start_guide.md
  - API Docs:
      - API Documentation: api/index.md
      - Datatypes:
          - Datatypes: api/datatypes/index.md
          - Unsigned Integers: api/datatypes/numbers/uints.md
          - Signed Integers: api/datatypes/numbers/ints.md
          - Floating Points: api/datatypes/numbers/floats.md
          - Range: api/datatypes/generics/range.md
          - Tables:
              - Table Datatypes: api/datatypes/generics/tables/index.md
              - Array: api/datatypes/generics/tables/arr.md
              - Map: api/datatypes/generics/tables/map.md
              - Struct: api/datatypes/generics/tables/struct.md
          - VLQ: api/datatypes/generics/vlq.md
          - Bool: api/datatypes/bool.md
          - String: api/datatypes/generics/str.md
          - Optional: api/datatypes/generics/optional.md
          - Literal: api/datatypes/generics/literal.md
          - Vect3: api/datatypes/generics/vect3.md
          - Vect2: api/datatypes/generics/vect2.md
          - Roblox Vect2: api/datatypes/generics/roblox_vect2.md
          - CFrame: api/datatypes/generics/cframe.md
          - Enums: api/datatypes/generics/enums.md
          - Clamp: api/datatypes/generics/clamp.md
          - Any: api/datatypes/any.md
          - Instances: api/datatypes/instances.md
          - Checked: api/datatypes/generics/checked.md
          - Cached Datatypes: api/datatypes/generics/cached.md
          - Computed: api/datatypes/generics/computed.md
          - Buffer: api/datatypes/generics/buff.md
      - Begin Replication: api/begin_replication.md
      - Step Replication: api/step_replication.md
      - Messages:
          - container: api/network/messages/creation/container.md
          - message: api/network/messages/creation/message.md
          - connect: api/network/messages/listening/connect.md
          - disconnect: api/network/messages/listening/disconnect.md
          - connect_sync: api/network/messages/listening/connect_sync.md
          - Sending:
              - send: api/network/messages/sending/send.md
              - broadcast: api/network/messages/sending/broadcast.md
              - broadcast_to_all: api/network/messages/sending/broadcast_to_all.md
              - broadcast_to_all_except: api/network/messages/sending/broadcast_to_all_except.md
              - send_unreliably: api/network/messages/sending/send_unreliably.md
              - broadcast_unreliably: api/network/messages/sending/broadcast_unreliably.md
              - broadcast_unreliably_to_all: api/network/messages/sending/broadcast_unreliably_to_all.md
              - broadcast_unreliably_to_all_except: api/network/messages/sending/broadcast_unreliably_to_all_except.md
      - Stfu: api/stfu.md
      - Security API:
          - api/security/index.md
          - Hooks:
              - api/security/hooks/index.md
          - Actions:
              - api/security/actions/index.md
          - Triggers:
              - api/security/triggers/index.md
          - get_active_client: api/security/get_active_client.md
      - Internal API:
          - api/internals/index.md
          - Input: api/internals/io/input.md
          - Output: api/internals/io/output.md
          - Writer:
              - DynamicWriter: api/internals/io/writer/index.md
              - From Size: api/internals/io/writer/writer_from_size.md
              - From Buff: api/internals/io/writer/writer_from_buff.md
              - Get Buff: api/internals/io/writer/get_writer_buff.md
              - Try Realloc: api/internals/io/writer/try_realloc.md
              - Set Byte Ptr: api/internals/io/writer/set_byte_ptr.md
              - Get Byte Ptr: api/internals/io/writer/get_byte_ptr.md
          - Get Holy: api/internals/get_holy.md

  - Performance:
      - Performance: blog/performance/index.md
  - Internals Blog:
      - Internals Blog: blog/internals/index.md
      - Holy:
          - Holy: blog/internals/holy/index.md
          - Cached Closures: blog/internals/holy/cached_closures.md
          - Special Cased Generics: blog/internals/holy/special_cased_generics.md
          - Reallocation Merging: blog/internals/holy/reallocation_merging.md
      - Message Sync: blog/internals/message_sync.md
      - Unreliable Fragmentation: blog/internals/unreliable_fragmentation.md
      - Replication Batch: blog/internals/replication_format.md
      - CFrame Encoding: blog/internals/cframe_encoding.md
      - Dynamic Streams: blog/internals/dynamic_streams.md
      - Bitpacks: blog/internals/bitpacks.md
  - Contributing:
    - Contributing: contributing/index.md
    - Style Guide: contributing/STYLE.md
